'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type ArticleStatus = 'draft' | 'review' | 'scheduled' | 'published' | 'archived';
type PrimaryItemType = 'bill' | 'law' | 'executive_order' | 'cluster';

interface AdminArticle {
  id: number;
  title: string;
  slug: string | null;
  status: ArticleStatus;
  summary: string | null;
  excerpt: string | null;
  dek: string | null;
  author: string | null;
  auto_generated: boolean;
  is_featured: boolean;
  featured_until: string | null;
  primary_item_type: PrimaryItemType;
  primary_item_id: number;
  generated_at: string | null;
  published_at: string | null;
  updated_at: string | null;
  source_urls: string[];
  prompt_template: string | null;
  agent_identifier: string | null;
  generation_metadata: Record<string, unknown> | null;
  views_count: number | null;
  clickthroughs: number | null;
  reading_time: number | null;
  editor_notes?: string | null;
  body_markdown?: string | null;
  body?: {
    sections?: Array<{
      heading: string;
      bullets?: string[];
    }>;
  } | null;
}

interface PaginationState {
  page: number;
  perPage: number;
  total: number;
  totalPages: number;
}

interface FormState {
  title: string;
  dek: string;
  summary: string;
  excerpt: string;
  slug: string;
  author: string;
  editor_notes: string;
  is_featured: boolean;
  featured_until: string;
  status: ArticleStatus;
}

const STATUS_LABELS: Record<ArticleStatus, string> = {
  draft: 'Draft',
  review: 'In Review',
  scheduled: 'Scheduled',
  published: 'Published',
  archived: 'Archived',
};

const TYPE_LABELS: Record<PrimaryItemType, string> = {
  bill: 'Bill',
  law: 'Law',
  executive_order: 'Executive Order',
  cluster: 'Supreme Court Case',
};

const STATUS_FILTERS: Array<{ value: 'all' | ArticleStatus; label: string }> = [
  { value: 'all', label: 'All statuses' },
  { value: 'draft', label: 'Draft' },
  { value: 'review', label: 'In review' },
  { value: 'scheduled', label: 'Scheduled' },
  { value: 'published', label: 'Published' },
  { value: 'archived', label: 'Archived' },
];

const TYPE_FILTERS: Array<{ value: 'all' | PrimaryItemType; label: string }> = [
  { value: 'all', label: 'All types' },
  { value: 'bill', label: 'Bills' },
  { value: 'law', label: 'Laws' },
  { value: 'executive_order', label: 'Executive Orders' },
  { value: 'cluster', label: 'Supreme Court Cases' },
];

const AUTO_FILTERS = [
  { value: 'all', label: 'All origins' },
  { value: 'true', label: 'Auto generated' },
  { value: 'false', label: 'Editor written' },
];

const DEFAULT_PAGINATION: PaginationState = {
  page: 1,
  perPage: 25,
  total: 0,
  totalPages: 1,
};

function formatDateTime(value: string | null) {
  if (!value) return '--';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }
  return date.toLocaleString();
}

function toInputDateTime(value: string | null) {
  if (!value) return '';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  const offset = date.getTimezoneOffset();
  const local = new Date(date.getTime() - offset * 60 * 1000);
  return local.toISOString().slice(0, 16);
}

function fromInputDateTime(value: string) {
  if (!value) return null;
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return null;
  return date.toISOString();
}

function buildFormState(article: AdminArticle): FormState {
  return {
    title: article.title ?? '',
    dek: article.dek ?? '',
    summary: article.summary ?? '',
    excerpt: article.excerpt ?? '',
    slug: article.slug ?? '',
    author: article.author ?? '',
    editor_notes: article.editor_notes ?? '',
    is_featured: Boolean(article.is_featured),
    featured_until: toInputDateTime(article.featured_until),
    status: article.status,
  };
}

function mergeArticleList(articles: AdminArticle[], updated: AdminArticle): AdminArticle[] {
  return articles.map((item) => (item.id === updated.id ? { ...item, ...updated } : item));
}

export default function ArticlesAdminPage() {
  const [articles, setArticles] = useState<AdminArticle[]>([]);
  const [pagination, setPagination] = useState<PaginationState>(DEFAULT_PAGINATION);
  const [filters, setFilters] = useState({
    status: 'all' as 'all' | ArticleStatus,
    primaryItemType: 'all' as 'all' | PrimaryItemType,
    autoGenerated: 'all' as 'all' | 'true' | 'false',
    page: 1,
    perPage: DEFAULT_PAGINATION.perPage,
    search: '',
  });
  const [searchInput, setSearchInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [alert, setAlert] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const [selectedArticle, setSelectedArticle] = useState<AdminArticle | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [formState, setFormState] = useState<FormState | null>(null);
  const [dirtyFields, setDirtyFields] = useState<Set<keyof FormState>>(new Set());
  const [saving, setSaving] = useState(false);

  const statusFilterValue = filters.status;
  const typeFilterValue = filters.primaryItemType;
  const autoFilterValue = filters.autoGenerated;

  useEffect(() => {
    const handler = setTimeout(() => {
      setFilters((prev) => ({
        ...prev,
        search: searchInput.trim(),
        page: 1,
      }));
    }, 400);
    return () => clearTimeout(handler);
  }, [searchInput]);

  const fetchArticles = useCallback(async () => {
    try {
      setLoading(true);
      setAlert(null);
      const params = new URLSearchParams();
      if (filters.status !== 'all') params.set('status', filters.status);
      if (filters.primaryItemType !== 'all') params.set('primaryItemType', filters.primaryItemType);
      if (filters.autoGenerated !== 'all') params.set('autoGenerated', filters.autoGenerated);
      if (filters.search) params.set('search', filters.search);
      params.set('page', String(filters.page));
      params.set('limit', String(filters.perPage));

      const response = await fetch(`/api/admin/articles?${params.toString()}`, {
        cache: 'no-store',
      });

      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.error || 'Failed to load articles');
      }

      setArticles(payload.articles || []);
      setPagination(
        payload.pagination || {
          page: filters.page,
          perPage: filters.perPage,
          total: payload.articles ? payload.articles.length : 0,
          totalPages: 1,
        },
      );
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to load articles';
      setAlert({ type: 'error', message });
    } finally {
      setLoading(false);
    }
  }, [filters]);

  useEffect(() => {
    fetchArticles();
  }, [fetchArticles]);

  const resetSelection = () => {
    setSelectedArticle(null);
    setFormState(null);
    setDetailLoading(false);
    setDirtyFields(new Set());
  };

  const openArticleDetail = async (article: AdminArticle) => {
    try {
      setDetailLoading(true);
      setAlert(null);

      const response = await fetch(`/api/admin/articles?id=${article.id}`, {
        cache: 'no-store',
      });
      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.error || 'Failed to load article detail');
      }

      const detail: AdminArticle = payload.article;
      setSelectedArticle(detail);
      setFormState(buildFormState(detail));
      setDirtyFields(new Set());
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to load article detail';
      setAlert({ type: 'error', message });
    } finally {
      setDetailLoading(false);
    }
  };

  const markDirty = (field: keyof FormState) => {
    setDirtyFields((prev) => {
      const next = new Set(prev);
      next.add(field);
      return next;
    });
  };

  const updateFormState = <K extends keyof FormState>(field: K, value: FormState[K]) => {
    setFormState((prev) => {
      if (!prev) return prev;
      if (prev[field] === value) return prev;
      const next = { ...prev, [field]: value };
      return next;
    });
    markDirty(field);
  };

  const applyArticleUpdate = (updated: AdminArticle) => {
    setSelectedArticle(updated);
    setFormState(buildFormState(updated));
    setDirtyFields(new Set());
    setArticles((prev) => mergeArticleList(prev, updated));
  };

  const sendUpdates = async (updates: Record<string, unknown>, successMessage = 'Article updated') => {
    if (!selectedArticle) return;
    try {
      setSaving(true);
      setAlert(null);

      const response = await fetch('/api/admin/articles', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: selectedArticle.id, updates }),
      });
      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload?.error || 'Failed to update article');
      }

      const updated: AdminArticle = payload.article;
      applyArticleUpdate(updated);
      setAlert({ type: 'success', message: successMessage });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to update article';
      setAlert({ type: 'error', message });
    } finally {
      setSaving(false);
    }
  };

  const handleSave = async () => {
    if (!formState || !selectedArticle) return;
    if (dirtyFields.size === 0) {
      setAlert({ type: 'success', message: 'No changes to save' });
      return;
    }

    const updates: Record<string, unknown> = {};
    dirtyFields.forEach((field) => {
      switch (field) {
        case 'title':
          updates.title = formState.title;
          break;
        case 'dek':
          updates.dek = formState.dek;
          break;
        case 'summary':
          updates.summary = formState.summary;
          break;
        case 'excerpt':
          updates.excerpt = formState.excerpt;
          break;
        case 'slug':
          updates.slug = formState.slug.trim().length > 0 ? formState.slug.trim() : null;
          break;
        case 'author':
          updates.author = formState.author.trim().length > 0 ? formState.author.trim() : null;
          break;
        case 'editor_notes':
          updates.editor_notes = formState.editor_notes.trim().length > 0 ? formState.editor_notes.trim() : null;
          break;
        case 'is_featured':
          updates.is_featured = formState.is_featured;
          break;
        case 'featured_until':
          updates.featured_until = formState.featured_until ? fromInputDateTime(formState.featured_until) : null;
          break;
        case 'status':
          updates.status = formState.status;
          break;
        default:
          break;
      }
    });

    if (Object.keys(updates).length === 0) {
      setAlert({ type: 'success', message: 'No changes to save' });
      return;
    }

    await sendUpdates(updates);
    fetchArticles();
  };

  const handleStatusChange = async (newStatus: ArticleStatus, note?: string) => {
    if (!selectedArticle) return;
    const updates: Record<string, unknown> = { status: newStatus };
    if (newStatus === 'scheduled' && formState?.featured_until) {
      updates.published_at = fromInputDateTime(formState.featured_until);
    }
    await sendUpdates(updates, note || `Status set to ${STATUS_LABELS[newStatus]}`);
    fetchArticles();
  };

  const canSave = useMemo(() => dirtyFields.size > 0 && !saving, [dirtyFields, saving]);

  const renderBody = () => {
    if (!selectedArticle) return null;
    const sections = selectedArticle.body?.sections;
    if (!sections || sections.length === 0) {
      return <p className="text-sm text-gray-500">No structured body available.</p>;
    }
    return (
      <div className="space-y-4">
        {sections.map((section, index) => (
          <div key={`${section.heading}-${index}`} className="rounded-md border border-gray-200 p-3">
            <h4 className="text-sm font-semibold text-gray-800">{section.heading}</h4>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-gray-700">
              {(section.bullets ?? []).map((bullet, bulletIndex) => (
                <li key={bulletIndex}>{bullet}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    );
  };

  return (
    <div className="space-y-6 px-4 py-8">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-semibold text-gray-900">Articles</h1>
        <p className="text-sm text-gray-600">
          Review generated articles, make editorial edits, and control publication status.
        </p>
      </div>

      {alert && (
        <div
          className={[
            'rounded-md border px-4 py-3 text-sm',
            alert.type === 'success'
              ? 'border-green-300 bg-green-50 text-green-700'
              : 'border-red-300 bg-red-50 text-red-700',
          ].join(' ')}
        >
          {alert.message}
        </div>
      )}

      <div className="flex flex-wrap items-end gap-3 rounded-md border border-gray-200 bg-white p-4 shadow-sm">
        <div className="flex flex-col">
          <label className="text-xs font-medium uppercase text-gray-500">Status</label>
          <select
            value={statusFilterValue}
            onChange={(event) =>
              setFilters((prev) => ({
                ...prev,
                status: event.target.value as 'all' | ArticleStatus,
                page: 1,
              }))
            }
            className="mt-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
          >
            {STATUS_FILTERS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col">
          <label className="text-xs font-medium uppercase text-gray-500">Type</label>
          <select
            value={typeFilterValue}
            onChange={(event) =>
              setFilters((prev) => ({
                ...prev,
                primaryItemType: event.target.value as 'all' | PrimaryItemType,
                page: 1,
              }))
            }
            className="mt-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
          >
            {TYPE_FILTERS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-col">
          <label className="text-xs font-medium uppercase text-gray-500">Origin</label>
          <select
            value={autoFilterValue}
            onChange={(event) =>
              setFilters((prev) => ({
                ...prev,
                autoGenerated: event.target.value as 'all' | 'true' | 'false',
                page: 1,
              }))
            }
            className="mt-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
          >
            {AUTO_FILTERS.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        </div>

        <div className="flex flex-1 flex-col min-w-[220px]">
          <label className="text-xs font-medium uppercase text-gray-500">Search</label>
          <input
            type="search"
            value={searchInput}
            onChange={(event) => setSearchInput(event.target.value)}
            placeholder="Search by title or summary"
            className="mt-1 rounded-md border border-gray-300 px-3 py-2 text-sm"
          />
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setFilters((prev) => ({ ...prev }))}
            className="rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"
          >
            Refresh
          </button>
          <button
            type="button"
            onClick={() => {
              setFilters({
                status: 'draft',
                primaryItemType: 'all',
                autoGenerated: 'true',
                page: 1,
                perPage: DEFAULT_PAGINATION.perPage,
                search: '',
              });
              setSearchInput('');
            }}
            className="rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"
          >
            Draft queue
          </button>
        </div>
      </div>

      <div className="overflow-hidden rounded-lg border border-gray-200 bg-white shadow-sm">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Title
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Status
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Type
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Generated
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Published
              </th>
              <th className="px-6 py-3 text-left text-xs font-medium uppercase tracking-wider text-gray-500">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200 bg-white">
            {loading ? (
              <tr>
                <td className="px-6 py-8 text-center text-sm text-gray-500" colSpan={6}>
                  Loading articles...
                </td>
              </tr>
            ) : articles.length === 0 ? (
              <tr>
                <td className="px-6 py-8 text-center text-sm text-gray-500" colSpan={6}>
                  No articles match the selected filters.
                </td>
              </tr>
            ) : (
              articles.map((article) => (
                <tr key={article.id}>
                  <td className="max-w-md px-6 py-4 text-sm font-medium text-gray-900">
                    {article.title}
                    <div className="mt-1 flex flex-wrap gap-2 text-xs text-gray-500">
                      <span>#{article.id}</span>
                      {article.auto_generated ? <span className="rounded bg-blue-100 px-2 py-0.5 text-blue-700">Auto</span> : null}
                      {article.is_featured ? <span className="rounded bg-yellow-100 px-2 py-0.5 text-yellow-800">Featured</span> : null}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-700">{STATUS_LABELS[article.status]}</td>
                  <td className="px-6 py-4 text-sm text-gray-700">{TYPE_LABELS[article.primary_item_type]}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{formatDateTime(article.generated_at)}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{formatDateTime(article.published_at)}</td>
                  <td className="px-6 py-4 text-sm text-right">
                    <button
                      type="button"
                      onClick={() => openArticleDetail(article)}
                      className="rounded-md border border-gray-300 px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-100"
                    >
                      Review
                    </button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <div className="flex items-center justify-between text-sm text-gray-600">
        <div>
          Showing {(pagination.page - 1) * pagination.perPage + 1}-
          {Math.min(pagination.page * pagination.perPage, pagination.total)} of {pagination.total}
        </div>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() =>
              setFilters((prev) => ({
                ...prev,
                page: Math.max(1, prev.page - 1),
              }))
            }
            disabled={pagination.page <= 1}
            className="rounded-md border border-gray-300 px-3 py-1.5 disabled:opacity-50"
          >
            Previous
          </button>
          <span>
            Page {pagination.page} of {pagination.totalPages}
          </span>
          <button
            type="button"
            onClick={() =>
              setFilters((prev) => ({
                ...prev,
                page: Math.min(pagination.totalPages, prev.page + 1),
              }))
            }
            disabled={pagination.page >= pagination.totalPages}
            className="rounded-md border border-gray-300 px-3 py-1.5 disabled:opacity-50"
          >
            Next
          </button>
        </div>
      </div>

      {selectedArticle && formState ? (
        <div className="fixed inset-0 z-30 bg-black/40">
          <div className="absolute inset-y-0 right-0 w-full max-w-3xl overflow-y-auto bg-white shadow-2xl">
            <div className="flex items-center justify-between border-b border-gray-200 px-6 py-4">
              <div>
                <h2 className="text-xl font-semibold text-gray-900">Article #{selectedArticle.id}</h2>
                <p className="text-sm text-gray-600">
                  {TYPE_LABELS[selectedArticle.primary_item_type]} • Primary item ID {selectedArticle.primary_item_id}
                </p>
              </div>
              <button
                type="button"
                onClick={resetSelection}
                className="rounded-md border border-gray-300 px-3 py-1.5 text-sm text-gray-700 hover:bg-gray-100"
              >
                Close
              </button>
            </div>

            {detailLoading ? (
              <div className="p-6 text-sm text-gray-500">Loading article...</div>
            ) : (
              <div className="space-y-8 p-6">
                <section className="space-y-4">
                  <div className="flex flex-wrap gap-3">
                    <span className="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700">
                      Status: {STATUS_LABELS[selectedArticle.status]}
                    </span>
                    <span className="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700">
                      Generated: {formatDateTime(selectedArticle.generated_at)}
                    </span>
                    <span className="rounded bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700">
                      Published: {formatDateTime(selectedArticle.published_at)}
                    </span>
                    {selectedArticle.auto_generated ? (
                      <span className="rounded bg-blue-100 px-2 py-1 text-xs font-medium text-blue-800">Auto generated</span>
                    ) : null}
                  </div>

                  <div className="flex flex-wrap gap-3">
                    <button
                      type="button"
                      onClick={() => handleStatusChange('review', 'Moved to review')}
                      className="rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"
                      disabled={saving}
                    >
                      Mark as Review
                    </button>
                    <button
                      type="button"
                      onClick={() => handleStatusChange('published', 'Article published')}
                      className="rounded-md border border-green-400 bg-green-50 px-3 py-2 text-sm text-green-700 hover:bg-green-100 disabled:opacity-50"
                      disabled={saving || selectedArticle.status === 'published'}
                    >
                      Publish now
                    </button>
                    <button
                      type="button"
                      onClick={() => handleStatusChange('draft', 'Article returned to draft')}
                      className="rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 disabled:opacity-50"
                      disabled={saving || selectedArticle.status === 'draft'}
                    >
                      Unpublish
                    </button>
                    <button
                      type="button"
                      onClick={() => handleStatusChange('archived', 'Article archived')}
                      className="rounded-md border border-red-300 px-3 py-2 text-sm text-red-700 hover:bg-red-50 disabled:opacity-50"
                      disabled={saving}
                    >
                      Archive
                    </button>
                  </div>
                </section>

                <section className="space-y-4">
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Title</label>
                    <input
                      type="text"
                      value={formState.title}
                      onChange={(event) => updateFormState('title', event.target.value)}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Dek</label>
                    <textarea
                      value={formState.dek}
                      onChange={(event) => updateFormState('dek', event.target.value)}
                      rows={2}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Summary</label>
                    <textarea
                      value={formState.summary}
                      onChange={(event) => updateFormState('summary', event.target.value)}
                      rows={3}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Excerpt</label>
                    <textarea
                      value={formState.excerpt}
                      onChange={(event) => updateFormState('excerpt', event.target.value)}
                      rows={3}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    />
                  </div>
                </section>

                <section className="grid gap-4 md:grid-cols-2">
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Slug</label>
                    <input
                      type="text"
                      value={formState.slug}
                      onChange={(event) => updateFormState('slug', event.target.value)}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                      placeholder="custom-slug"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Author</label>
                    <input
                      type="text"
                      value={formState.author}
                      onChange={(event) => updateFormState('author', event.target.value)}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                      placeholder="Display author name"
                    />
                  </div>
                  <div>
                    <label className="text-xs font-medium uppercase text-gray-500">Feature until</label>
                    <input
                      type="datetime-local"
                      value={formState.featured_until}
                      onChange={(event) => updateFormState('featured_until', event.target.value)}
                      className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    />
                  </div>
                  <div className="flex items-center gap-2 pt-6">
                    <input
                      id="feature-toggle"
                      type="checkbox"
                      checked={formState.is_featured}
                      onChange={(event) => updateFormState('is_featured', event.target.checked)}
                      className="h-4 w-4"
                    />
                    <label htmlFor="feature-toggle" className="text-sm text-gray-700">
                      Mark as featured
                    </label>
                  </div>
                </section>

                <section className="space-y-2">
                  <label className="text-xs font-medium uppercase text-gray-500">Editor notes</label>
                  <textarea
                    value={formState.editor_notes}
                    onChange={(event) => updateFormState('editor_notes', event.target.value)}
                    rows={3}
                    className="mt-1 w-full rounded-md border border-gray-300 px-3 py-2 text-sm"
                    placeholder="Leave context or follow-up notes for the editorial team."
                  />
                </section>

                <section className="space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-semibold text-gray-900">Article body</h3>
                    {selectedArticle.source_urls && selectedArticle.source_urls.length > 0 ? (
                      <Link
                        href={selectedArticle.source_urls[0]}
                        target="_blank"
                        rel="noreferrer"
                        className="text-sm text-blue-600 hover:text-blue-800"
                      >
                        View source
                      </Link>
                    ) : null}
                  </div>
                  {renderBody()}
                  {selectedArticle.body_markdown ? (
                    <div>
                      <h4 className="text-sm font-semibold text-gray-800">Markdown</h4>
                      <pre className="mt-2 max-h-64 overflow-auto rounded-md bg-gray-100 p-3 text-xs text-gray-700">
                        {selectedArticle.body_markdown}
                      </pre>
                    </div>
                  ) : null}
                </section>

                <section className="space-y-2">
                  <h3 className="text-sm font-semibold text-gray-800">Metadata</h3>
                  <div className="grid gap-2 text-xs text-gray-600 md:grid-cols-2">
                    <div>Slug: {selectedArticle.slug || '--'}</div>
                    <div>Agent: {selectedArticle.agent_identifier || '--'}</div>
                    <div>Prompt template: {selectedArticle.prompt_template || '--'}</div>
                    <div>Reading time: {selectedArticle.reading_time ?? '--'} min</div>
                    <div>Views: {selectedArticle.views_count ?? 0}</div>
                    <div>Clickthroughs: {selectedArticle.clickthroughs ?? 0}</div>
                  </div>
                  {selectedArticle.generation_metadata ? (
                    <pre className="mt-2 max-h-48 overflow-auto rounded-md bg-gray-100 p-3 text-xs text-gray-700">
                      {JSON.stringify(selectedArticle.generation_metadata, null, 2)}
                    </pre>
                  ) : null}
                </section>

                <div className="flex items-center justify-between border-t border-gray-200 pt-4">
                  <div className="text-xs text-gray-500">
                    Last updated {formatDateTime(selectedArticle.updated_at)}
                  </div>
                  <div className="flex gap-2">
                    <button
                      type="button"
                      onClick={handleSave}
                      disabled={!canSave}
                      className="rounded-md border border-blue-400 bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      {saving ? 'Saving...' : 'Save changes'}
                    </button>
                    <button
                      type="button"
                      onClick={resetSelection}
                      className="rounded-md border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  );
}
