-- Canonical, cross-branch GovSource topics and record assignments.
-- Source-native classifications such as bill.policy_area remain unchanged.
set search_path = public;

create table public.topic (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    parent_topic_id bigint references public.topic (id) on delete set null,
    slug text not null unique,
    name text not null unique,
    short_name text,
    description text not null,
    seo_title text not null,
    seo_description text not null,
    status text not null default 'draft',
    display_order smallint not null default 0,
    constraint topic_slug_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    constraint topic_name_check check (char_length(name) between 2 and 80),
    constraint topic_status_check check (status in ('draft', 'active', 'archived')),
    constraint topic_display_order_check check (display_order >= 0),
    constraint topic_no_self_parent_check check (parent_topic_id is distinct from id)
);

create index topic_parent_topic_id_idx
    on public.topic (parent_topic_id)
    where parent_topic_id is not null;

create index topic_public_directory_idx
    on public.topic (display_order, name)
    where status = 'active';

create table public.topic_source_mapping (
    topic_id bigint not null references public.topic (id) on delete cascade,
    source_system text not null,
    source_value text not null,
    is_primary boolean not null default true,
    created_at timestamptz not null default now(),
    primary key (source_system, source_value, topic_id),
    constraint topic_source_mapping_source_system_check check (
        source_system in ('congress_policy_area', 'brief_policy_area')
    ),
    constraint topic_source_mapping_source_value_check check (char_length(source_value) > 0)
);

create unique index topic_source_mapping_one_primary_idx
    on public.topic_source_mapping (source_system, source_value)
    where is_primary;

create index topic_source_mapping_topic_id_idx
    on public.topic_source_mapping (topic_id, source_system);

create table public.bill_topic (
    bill_id bigint not null references public.bill (id) on delete cascade,
    topic_id bigint not null references public.topic (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    assignment_source text not null,
    assignment_status text not null default 'suggested',
    confidence numeric(4, 3),
    is_primary boolean not null default false,
    evidence jsonb not null default '{}'::jsonb,
    assigned_by uuid references auth.users (id) on delete set null,
    reviewed_by uuid references auth.users (id) on delete set null,
    reviewed_at timestamptz,
    primary key (bill_id, topic_id),
    constraint bill_topic_assignment_source_check check (
        assignment_source in ('source_mapping', 'rule_based', 'ai_suggested', 'editorial')
    ),
    constraint bill_topic_assignment_status_check check (
        assignment_status in ('suggested', 'approved', 'rejected')
    ),
    constraint bill_topic_confidence_check check (confidence between 0 and 1),
    constraint bill_topic_evidence_check check (jsonb_typeof(evidence) = 'object')
);

create table public.agency_document_topic (
    agency_document_id bigint not null references public.agency_document (id) on delete cascade,
    topic_id bigint not null references public.topic (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    assignment_source text not null,
    assignment_status text not null default 'suggested',
    confidence numeric(4, 3),
    is_primary boolean not null default false,
    evidence jsonb not null default '{}'::jsonb,
    assigned_by uuid references auth.users (id) on delete set null,
    reviewed_by uuid references auth.users (id) on delete set null,
    reviewed_at timestamptz,
    primary key (agency_document_id, topic_id),
    constraint agency_document_topic_assignment_source_check check (
        assignment_source in ('source_mapping', 'rule_based', 'ai_suggested', 'editorial')
    ),
    constraint agency_document_topic_assignment_status_check check (
        assignment_status in ('suggested', 'approved', 'rejected')
    ),
    constraint agency_document_topic_confidence_check check (confidence between 0 and 1),
    constraint agency_document_topic_evidence_check check (jsonb_typeof(evidence) = 'object')
);

create table public.cluster_topic (
    cluster_id bigint not null references public.cluster (id) on delete cascade,
    topic_id bigint not null references public.topic (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    assignment_source text not null,
    assignment_status text not null default 'suggested',
    confidence numeric(4, 3),
    is_primary boolean not null default false,
    evidence jsonb not null default '{}'::jsonb,
    assigned_by uuid references auth.users (id) on delete set null,
    reviewed_by uuid references auth.users (id) on delete set null,
    reviewed_at timestamptz,
    primary key (cluster_id, topic_id),
    constraint cluster_topic_assignment_source_check check (
        assignment_source in ('source_mapping', 'rule_based', 'ai_suggested', 'editorial')
    ),
    constraint cluster_topic_assignment_status_check check (
        assignment_status in ('suggested', 'approved', 'rejected')
    ),
    constraint cluster_topic_confidence_check check (confidence between 0 and 1),
    constraint cluster_topic_evidence_check check (jsonb_typeof(evidence) = 'object')
);

create table public.brief_topic (
    brief_id bigint not null references public.brief (id) on delete cascade,
    topic_id bigint not null references public.topic (id) on delete cascade,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    assignment_source text not null,
    assignment_status text not null default 'suggested',
    confidence numeric(4, 3),
    is_primary boolean not null default false,
    evidence jsonb not null default '{}'::jsonb,
    assigned_by uuid references auth.users (id) on delete set null,
    reviewed_by uuid references auth.users (id) on delete set null,
    reviewed_at timestamptz,
    primary key (brief_id, topic_id),
    constraint brief_topic_assignment_source_check check (
        assignment_source in ('source_mapping', 'rule_based', 'ai_suggested', 'editorial')
    ),
    constraint brief_topic_assignment_status_check check (
        assignment_status in ('suggested', 'approved', 'rejected')
    ),
    constraint brief_topic_confidence_check check (confidence between 0 and 1),
    constraint brief_topic_evidence_check check (jsonb_typeof(evidence) = 'object')
);

-- The composite primary keys serve record-to-topic lookups. These reverse
-- indexes support topic pages that fetch records of each type by topic.
create index bill_topic_topic_id_idx
    on public.bill_topic (topic_id, bill_id)
    where assignment_status = 'approved';
create unique index bill_topic_one_primary_idx
    on public.bill_topic (bill_id)
    where assignment_status = 'approved' and is_primary;
create index agency_document_topic_topic_id_idx
    on public.agency_document_topic (topic_id, agency_document_id)
    where assignment_status = 'approved';
create unique index agency_document_topic_one_primary_idx
    on public.agency_document_topic (agency_document_id)
    where assignment_status = 'approved' and is_primary;
create index cluster_topic_topic_id_idx
    on public.cluster_topic (topic_id, cluster_id)
    where assignment_status = 'approved';
create unique index cluster_topic_one_primary_idx
    on public.cluster_topic (cluster_id)
    where assignment_status = 'approved' and is_primary;
create index brief_topic_topic_id_idx
    on public.brief_topic (topic_id, brief_id)
    where assignment_status = 'approved';
create unique index brief_topic_one_primary_idx
    on public.brief_topic (brief_id)
    where assignment_status = 'approved' and is_primary;

insert into public.topic (
    slug, name, short_name, description, seo_title, seo_description, status, display_order
)
values
    ('agriculture-food', 'Agriculture & Food', 'Agriculture', 'Federal policy affecting farms, food production, nutrition, and agricultural markets.', 'Agriculture and Food Policy | GovSource', 'Track federal bills, laws, executive actions, regulations, and court cases concerning agriculture and food.', 'active', 10),
    ('culture-society', 'Culture & Society', 'Culture', 'Federal actions involving arts, culture, religion, recreation, history, and public commemorations.', 'Culture and Society Policy | GovSource', 'Explore federal legislation, executive actions, regulations, and cases involving culture and society.', 'active', 20),
    ('civil-rights', 'Civil Rights', 'Civil Rights', 'Federal protections and disputes involving constitutional rights, liberties, discrimination, and equal treatment.', 'Civil Rights Policy and Cases | GovSource', 'Follow federal civil-rights bills, laws, executive actions, regulations, and Supreme Court cases.', 'active', 30),
    ('commerce-consumer-affairs', 'Commerce & Consumer Affairs', 'Commerce', 'Federal policy governing businesses, markets, competition, commerce, and consumer protection.', 'Commerce and Consumer Policy | GovSource', 'Track federal commerce and consumer-protection legislation, regulations, executive actions, and cases.', 'active', 40),
    ('economy-finance', 'Economy & Finance', 'Economy', 'Federal fiscal, monetary, banking, securities, insurance, and broader economic policy.', 'Economy and Finance Policy | GovSource', 'Follow federal economic and financial bills, laws, regulations, executive actions, and court cases.', 'active', 50),
    ('education', 'Education', 'Education', 'Federal policy affecting schools, higher education, student aid, training, and educational access.', 'Education Policy | GovSource', 'Track federal education bills, laws, executive actions, regulations, and Supreme Court cases.', 'active', 60),
    ('emergency-management', 'Emergency Management', 'Emergencies', 'Federal disaster preparedness, emergency response, recovery, and resilience policy.', 'Emergency Management Policy | GovSource', 'Follow federal emergency-management legislation, executive actions, regulations, and cases.', 'active', 70),
    ('energy', 'Energy', 'Energy', 'Federal policy affecting energy production, distribution, markets, reliability, and transition.', 'Energy Policy | GovSource', 'Track federal energy bills, laws, executive actions, regulations, and court cases.', 'active', 80),
    ('environment-climate', 'Environment & Climate', 'Environment', 'Federal environmental protection, climate, conservation, water, pollution, and natural-resource policy.', 'Environment and Climate Policy | GovSource', 'Follow federal environmental and climate legislation, executive actions, regulations, and cases.', 'active', 90),
    ('families-social-welfare', 'Families & Social Welfare', 'Social Welfare', 'Federal policy affecting families, children, income support, benefits, and social services.', 'Families and Social Welfare Policy | GovSource', 'Track federal family and social-welfare bills, laws, executive actions, regulations, and cases.', 'active', 100),
    ('foreign-affairs-trade', 'Foreign Affairs & Trade', 'Foreign Affairs', 'Federal diplomacy, international institutions, sanctions, foreign assistance, and international trade policy.', 'Foreign Affairs and Trade Policy | GovSource', 'Follow federal foreign-affairs and trade legislation, executive actions, regulations, and cases.', 'active', 110),
    ('government-elections', 'Government Operations & Elections', 'Government', 'Federal government administration, public service, oversight, elections, campaigns, and democratic institutions.', 'Government Operations and Elections | GovSource', 'Track federal government-operations and elections bills, laws, executive actions, regulations, and cases.', 'active', 120),
    ('health', 'Health', 'Health', 'Federal health care, public health, medical research, insurance, and drug policy.', 'Health Policy | GovSource', 'Follow federal health bills, laws, executive actions, regulations, and Supreme Court cases.', 'active', 130),
    ('housing', 'Housing', 'Housing', 'Federal housing, homelessness, mortgages, community development, and fair-housing policy.', 'Housing Policy | GovSource', 'Track federal housing bills, laws, executive actions, regulations, and court cases.', 'active', 140),
    ('immigration', 'Immigration', 'Immigration', 'Federal immigration, citizenship, asylum, border, visa, and naturalization policy.', 'Immigration Policy | GovSource', 'Follow federal immigration bills, laws, executive actions, regulations, and Supreme Court cases.', 'active', 150),
    ('justice-courts', 'Justice & Courts', 'Justice', 'Federal criminal law, law enforcement, courts, sentencing, corrections, and legal procedure.', 'Justice and Courts Policy | GovSource', 'Track federal justice legislation, executive actions, regulations, and Supreme Court cases.', 'active', 160),
    ('labor', 'Labor', 'Labor', 'Federal employment, wages, workplace standards, unions, benefits, and worker-protection policy.', 'Labor and Employment Policy | GovSource', 'Follow federal labor bills, laws, executive actions, regulations, and court cases.', 'active', 170),
    ('national-security-defense', 'National Security & Defense', 'Defense', 'Federal defense, military, intelligence, homeland security, and national-security policy.', 'National Security and Defense Policy | GovSource', 'Track federal defense and national-security legislation, executive actions, regulations, and cases.', 'active', 180),
    ('public-lands-natural-resources', 'Public Lands & Natural Resources', 'Public Lands', 'Federal policy governing public lands, wildlife, forests, minerals, oceans, and resource stewardship.', 'Public Lands and Natural Resources | GovSource', 'Follow federal public-lands and natural-resource bills, executive actions, regulations, and cases.', 'active', 190),
    ('technology-cybersecurity', 'Technology & Cybersecurity', 'Technology', 'Federal technology, communications, privacy, artificial intelligence, cybersecurity, and space policy.', 'Technology and Cybersecurity Policy | GovSource', 'Track federal technology and cybersecurity legislation, executive actions, regulations, and cases.', 'active', 200),
    ('taxes', 'Taxes', 'Taxes', 'Federal individual, business, payroll, estate, and tax-administration policy.', 'Federal Tax Policy | GovSource', 'Follow federal tax bills, laws, executive actions, regulations, and court cases.', 'active', 210),
    ('transportation-infrastructure', 'Transportation & Infrastructure', 'Infrastructure', 'Federal aviation, roads, rail, transit, shipping, public works, and infrastructure policy.', 'Transportation and Infrastructure Policy | GovSource', 'Track federal transportation and infrastructure legislation, executive actions, regulations, and cases.', 'active', 220),
    ('tribal-indigenous-affairs', 'Tribal & Indigenous Affairs', 'Tribal Affairs', 'Federal policy involving Tribal nations, Native peoples, sovereignty, treaties, lands, and services.', 'Tribal and Indigenous Affairs | GovSource', 'Follow federal Tribal and Indigenous affairs legislation, executive actions, regulations, and cases.', 'active', 230);

insert into public.topic_source_mapping (topic_id, source_system, source_value)
select topic.id, 'congress_policy_area', mapping.source_value
from (
    values
        ('Agriculture and Food', 'agriculture-food'),
        ('Animals', 'public-lands-natural-resources'),
        ('Armed Forces and National Security', 'national-security-defense'),
        ('Arts, Culture, Religion', 'culture-society'),
        ('Civil Rights and Liberties, Minority Issues', 'civil-rights'),
        ('Commemorations', 'culture-society'),
        ('Commerce', 'commerce-consumer-affairs'),
        ('Congress', 'government-elections'),
        ('Crime and Law Enforcement', 'justice-courts'),
        ('Economics and Public Finance', 'economy-finance'),
        ('Education', 'education'),
        ('Emergency Management', 'emergency-management'),
        ('Energy', 'energy'),
        ('Environmental Protection', 'environment-climate'),
        ('Families', 'families-social-welfare'),
        ('Finance and Financial Sector', 'economy-finance'),
        ('Foreign Trade and International Finance', 'foreign-affairs-trade'),
        ('Government Operations and Politics', 'government-elections'),
        ('Health', 'health'),
        ('Housing and Community Development', 'housing'),
        ('Immigration', 'immigration'),
        ('International Affairs', 'foreign-affairs-trade'),
        ('Labor and Employment', 'labor'),
        ('Law', 'justice-courts'),
        ('Native Americans', 'tribal-indigenous-affairs'),
        ('Private Legislation', 'government-elections'),
        ('Public Lands and Natural Resources', 'public-lands-natural-resources'),
        ('Science, Technology, Communications', 'technology-cybersecurity'),
        ('Social Sciences and History', 'culture-society'),
        ('Social Welfare', 'families-social-welfare'),
        ('Sports and Recreation', 'culture-society'),
        ('Taxation', 'taxes'),
        ('Transportation and Public Works', 'transportation-infrastructure'),
        ('Water Resources Development', 'environment-climate')
) as mapping(source_value, topic_slug)
join public.topic on topic.slug = mapping.topic_slug;

-- Congress provides one predominant policy area per bill. Preserve it on the
-- bill row and translate it into one approved primary GovSource topic.
insert into public.bill_topic (
    bill_id,
    topic_id,
    assignment_source,
    assignment_status,
    confidence,
    is_primary,
    evidence,
    reviewed_at
)
select
    bill.id,
    mapping.topic_id,
    'source_mapping',
    'approved',
    1.000,
    true,
    jsonb_build_object(
        'source_system', mapping.source_system,
        'source_value', bill.policy_area
    ),
    now()
from public.bill
join public.topic_source_mapping mapping
  on mapping.source_system = 'congress_policy_area'
 and mapping.source_value = bill.policy_area
 and mapping.is_primary;

-- Keep future bill syncs aligned with the canonical mapping without replacing
-- any independently assigned editorial, rules-based, or AI-suggested topics.
create or replace function public.sync_bill_topics_from_policy_area()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
    delete from public.bill_topic
    where bill_id = new.id
      and assignment_source = 'source_mapping';

    insert into public.bill_topic (
        bill_id,
        topic_id,
        assignment_source,
        assignment_status,
        confidence,
        is_primary,
        evidence,
        reviewed_at
    )
    select
        new.id,
        mapping.topic_id,
        'source_mapping',
        'approved',
        1.000,
        not exists (
            select 1
            from public.bill_topic existing
            where existing.bill_id = new.id
              and existing.assignment_status = 'approved'
              and existing.is_primary
        ),
        jsonb_build_object(
            'source_system', mapping.source_system,
            'source_value', new.policy_area
        ),
        now()
    from public.topic_source_mapping mapping
    where mapping.source_system = 'congress_policy_area'
      and mapping.source_value = new.policy_area
      and mapping.is_primary;

    return new;
end;
$$;

create trigger sync_public_bill_topics_from_policy_area
after insert or update of policy_area on public.bill
for each row
execute function public.sync_bill_topics_from_policy_area();

alter table public.topic enable row level security;
alter table public.topic_source_mapping enable row level security;
alter table public.bill_topic enable row level security;
alter table public.agency_document_topic enable row level security;
alter table public.cluster_topic enable row level security;
alter table public.brief_topic enable row level security;

create policy "Public can read active topics"
on public.topic
for select
to anon, authenticated
using (status = 'active');

create policy "Public can read approved bill topics"
on public.bill_topic
for select
to anon, authenticated
using (
    assignment_status = 'approved'
    and exists (
        select 1 from public.topic
        where topic.id = bill_topic.topic_id
          and topic.status = 'active'
    )
);

create policy "Public can read approved agency document topics"
on public.agency_document_topic
for select
to anon, authenticated
using (
    assignment_status = 'approved'
    and exists (
        select 1 from public.topic
        where topic.id = agency_document_topic.topic_id
          and topic.status = 'active'
    )
);

create policy "Public can read approved court case topics"
on public.cluster_topic
for select
to anon, authenticated
using (
    assignment_status = 'approved'
    and exists (
        select 1 from public.topic
        where topic.id = cluster_topic.topic_id
          and topic.status = 'active'
    )
);

create policy "Public can read topics for live briefs"
on public.brief_topic
for select
to anon, authenticated
using (
    assignment_status = 'approved'
    and exists (
        select 1 from public.topic
        where topic.id = brief_topic.topic_id
          and topic.status = 'active'
    )
    and exists (
        select 1 from public.brief
        where brief.id = brief_topic.brief_id
          and brief.status in ('published', 'scheduled')
          and brief.slug is not null
          and brief.published_at is not null
          and brief.published_at <= now()
    )
);

revoke all on table
    public.topic,
    public.topic_source_mapping,
    public.bill_topic,
    public.agency_document_topic,
    public.cluster_topic,
    public.brief_topic
from anon, authenticated;

grant select on table
    public.topic,
    public.bill_topic,
    public.agency_document_topic,
    public.cluster_topic,
    public.brief_topic
to anon, authenticated;

grant all on table
    public.topic,
    public.topic_source_mapping,
    public.bill_topic,
    public.agency_document_topic,
    public.cluster_topic,
    public.brief_topic
to service_role;

grant usage, select on sequence public.topic_id_seq to service_role;

revoke execute on function public.sync_bill_topics_from_policy_area()
from public, anon, authenticated;
grant execute on function public.sync_bill_topics_from_policy_area()
to service_role;

comment on table public.topic is
    'GovSource-owned cross-branch taxonomy used by canonical topic pages.';
comment on table public.topic_source_mapping is
    'Mappings from source-native classifications to canonical GovSource topics.';
comment on column public.bill.policy_area is
    'Predominant policy area supplied by Congress.gov; preserved as source-native data.';
