-- Replace the legacy long-form article model with structured, source-linked Briefs.
set search_path = public;

drop table if exists public.article_related_item cascade;
drop table if exists public.article cascade;
drop function if exists public.set_article_updated_at();

create table public.brief (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    created_by uuid references auth.users (id) on delete set null,
    updated_by uuid references auth.users (id) on delete set null,
    version integer not null default 1,
    status text not null default 'draft',
    title text not null,
    slug text,
    dek text,
    points jsonb not null default '[]'::jsonb,
    context_markdown text,
    primary_item_type text not null,
    primary_item_id bigint not null,
    policy_areas text[] not null default '{}',
    sources jsonb not null default '[]'::jsonb,
    author_name text,
    editor_notes text,
    published_at timestamptz,
    is_featured boolean not null default false,
    featured_until timestamptz,
    auto_generated boolean not null default false,
    generation_metadata jsonb,
    constraint brief_status_check check (
        status in ('draft', 'review', 'scheduled', 'published', 'archived')
    ),
    constraint brief_primary_item_type_check check (
        primary_item_type in ('bill', 'law', 'agency_document', 'cluster', 'executive_order')
    ),
    constraint brief_version_check check (version > 0),
    constraint brief_title_check check (char_length(title) between 1 and 180),
    constraint brief_dek_check check (dek is null or char_length(dek) <= 360),
    constraint brief_points_shape_check check (
        jsonb_typeof(points) = 'array' and jsonb_array_length(points) <= 5
    ),
    constraint brief_sources_shape_check check (jsonb_typeof(sources) = 'array'),
    constraint brief_publish_ready_check check (
        status not in ('published', 'scheduled')
        or (
            slug is not null
            and published_at is not null
            and dek is not null
            and jsonb_array_length(points) between 3 and 5
        )
    )
);

create unique index brief_slug_unique_idx
    on public.brief (slug)
    where slug is not null;

create index brief_public_feed_idx
    on public.brief (published_at desc, id desc)
    where status in ('published', 'scheduled');

create index brief_primary_item_idx
    on public.brief (primary_item_type, primary_item_id);

create index brief_featured_idx
    on public.brief (is_featured desc, featured_until, published_at desc);

create index brief_policy_areas_idx
    on public.brief using gin (policy_areas);

create table public.brief_related_item (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    brief_id bigint not null references public.brief (id) on delete cascade,
    item_type text not null,
    item_id bigint not null,
    relation_role text,
    sort_order smallint not null default 0,
    constraint brief_related_item_type_check check (
        item_type in ('bill', 'law', 'agency_document', 'cluster', 'executive_order')
    ),
    constraint brief_related_item_sort_order_check check (sort_order >= 0),
    constraint brief_related_item_unique unique (brief_id, item_type, item_id)
);

create index brief_related_item_brief_idx
    on public.brief_related_item (brief_id, sort_order);

create index brief_related_item_lookup_idx
    on public.brief_related_item (item_type, item_id);

create or replace function public.set_brief_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    new.version = old.version + 1;
    return new;
end;
$$;

create trigger set_public_brief_updated_at
before update on public.brief
for each row
execute function public.set_brief_updated_at();

alter table public.brief enable row level security;
alter table public.brief_related_item enable row level security;

create policy "Public can read live briefs"
on public.brief
for select
to anon, authenticated
using (
    status in ('published', 'scheduled')
    and slug is not null
    and published_at is not null
    and published_at <= now()
);

create policy "Public can read related items for live briefs"
on public.brief_related_item
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.brief
        where brief.id = brief_related_item.brief_id
          and brief.status in ('published', 'scheduled')
          and brief.slug is not null
          and brief.published_at is not null
          and brief.published_at <= now()
    )
);

grant select on table public.brief, public.brief_related_item to anon, authenticated;
revoke insert, update, delete on table public.brief, public.brief_related_item from anon, authenticated;
