"""Add BillText

Revision ID: 04194e790d0f
Revises: 3bfff90c799a
Create Date: 2025-03-23 19:19:30.112815

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04194e790d0f"
down_revision = "3bfff90c799a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
