"""Add term model

Revision ID: 1638ca10c707
Revises: 84bcf83db892
Create Date: 2025-03-29 14:21:16.137354

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1638ca10c707"
down_revision = "84bcf83db892"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "congressman_terms",
        sa.Column("congressman_id", sa.Integer(), nullable=True),
        sa.Column("congress", sa.Integer(), nullable=True),
        sa.Column(
            "chamber",
            postgresql.ENUM("HOUSE", "SENATE", name="chamber", create_type=False),
            nullable=False,
        ),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("state_code", sa.String(length=2), nullable=True),
        sa.Column("state_name", sa.String(length=50), nullable=True),
        sa.Column("district", sa.String(length=10), nullable=True),
        sa.Column("member_type", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["congressman_id"],
            ["congressmen.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("congressman_id", "congress", "chamber", name="uix_congressman_term"),
    )
    op.create_index(
        op.f("ix_congressman_terms_congressman_id"),
        "congressman_terms",
        ["congressman_id"],
        unique=False,
    )
    op.create_index(op.f("ix_congressman_terms_id"), "congressman_terms", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_congressman_terms_id"), table_name="congressman_terms")
    op.drop_index(op.f("ix_congressman_terms_congressman_id"), table_name="congressman_terms")
    op.drop_table("congressman_terms")
    # ### end Alembic commands ###
