"""Add users and laws

Revision ID: 16fa31a5d2fb
Revises: d02727f3fef4
Create Date: 2025-03-29 13:46:38.098373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "16fa31a5d2fb"
down_revision = "d02727f3fef4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
