"""Redefine billtext

Revision ID: 3bfff90c799a
Revises: 81288a46259d
Create Date: 2025-03-23 19:19:10.676667

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3bfff90c799a"
down_revision = "81288a46259d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bill_texts_bill_id", table_name="bill_texts")
    op.drop_index("ix_bill_texts_id", table_name="bill_texts")
    op.drop_table("bill_texts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_texts",
        sa.Column("bill_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("pdf_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "formatted_text_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("xml_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["bill_id"], ["bills.id"], name="bill_texts_bill_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="bill_texts_pkey"),
        sa.UniqueConstraint("bill_id", "type", name="uix_bill_type"),
    )
    op.create_index("ix_bill_texts_id", "bill_texts", ["id"], unique=False)
    op.create_index("ix_bill_texts_bill_id", "bill_texts", ["bill_id"], unique=False)
    # ### end Alembic commands ###
