"""Add HTML field

Revision ID: 4723c7d8b6e8
Revises: f5dde0776bb6
Create Date: 2025-03-23 20:21:53.347381

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4723c7d8b6e8"
down_revision = "f5dde0776bb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bill_texts", sa.Column("html_content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_texts", "html_content")
    # ### end Alembic commands ###
