"""Drop text lilnks

Revision ID: 57c00bca2804
Revises: 96f338c50772
Create Date: 2025-03-23 10:44:49.570119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57c00bca2804"
down_revision = "96f338c50772"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "most_recent_formatted_text_url")
    op.drop_column("bills", "most_recent_congress_pdf_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills",
        sa.Column(
            "most_recent_congress_pdf_url",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bills",
        sa.Column(
            "most_recent_formatted_text_url",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
