"""Drop status

Revision ID: 57e9c9aa91b0
Revises: c685083c2c91
Create Date: 2025-03-23 10:39:31.679427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57e9c9aa91b0"
down_revision = "c685083c2c91"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills",
        sa.Column("status", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
