"""Add user authentication models

Revision ID: 72c597951ab3
Revises: 4723c7d8b6e8
Create Date: 2025-03-27 21:51:35.123567

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72c597951ab3"
down_revision = "4723c7d8b6e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
