"""Alter unique constraint on text versions

Revision ID: 81288a46259d
Revises: f403e3aaf73e
Create Date: 2025-03-23 16:12:03.260371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81288a46259d"
down_revision = "f403e3aaf73e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_bill_text_version", "bill_texts", type_="unique")
    op.create_unique_constraint("uix_bill_type", "bill_texts", ["bill_id", "type"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_bill_type", "bill_texts", type_="unique")
    op.create_unique_constraint(
        "uix_bill_text_version", "bill_texts", ["bill_id", "date"]
    )
    # ### end Alembic commands ###
