"""Initial 2

Revision ID: 83ddeb287674
Revises: c0d1ede64f41
Create Date: 2025-03-23 09:27:43.628500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83ddeb287674"
down_revision = "c0d1ede64f41"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
