"""increase_version_code_column_size

Revision ID: 84bcf83db892
Revises: 16fa31a5d2fb
Create Date: 2025-03-29 13:54:52.139500

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "84bcf83db892"
down_revision = "16fa31a5d2fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "law_texts",
        "version_code",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "law_texts",
        "version_code",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
