"""Drop billtext again

Revision ID: 8fea8f4d78fd
Revises: c48e2a25ce55
Create Date: 2025-03-23 19:26:03.232111

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8fea8f4d78fd"
down_revision = "c48e2a25ce55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
