"""Drop summary

Revision ID: 96f338c50772
Revises: 57e9c9aa91b0
Create Date: 2025-03-23 10:41:40.536361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "96f338c50772"
down_revision = "57e9c9aa91b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills", sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
