"""Nullable end year on term

Revision ID: b326cf59f395
Revises: 1638ca10c707
Create Date: 2025-03-29 14:28:36.886646

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b326cf59f395"
down_revision = "1638ca10c707"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
