"""Drop short title

Revision ID: bdd4d48989bd
Revises: 57c00bca2804
Create Date: 2025-03-23 10:48:16.624706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bdd4d48989bd"
down_revision = "57c00bca2804"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "short_title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills",
        sa.Column(
            "short_title", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
