"""Initial

Revision ID: c0d1ede64f41
Revises: 
Create Date: 2025-03-23 09:25:15.314888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d1ede64f41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('congress', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.String(length=20), nullable=True),
    sa.Column('bill_type', sa.String(length=10), nullable=True),
    sa.Column('bill_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('short_title', sa.String(length=500), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('most_recent_formatted_text_url', sa.String(length=255), nullable=True),
    sa.Column('most_recent_congress_pdf_url', sa.String(length=255), nullable=True),
    sa.Column('policy_areas', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_bill_id'), 'bills', ['bill_id'], unique=True)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    op.create_table('congressmen',
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('party', sa.Enum('DEMOCRAT', 'REPUBLICAN', 'INDEPENDENT', 'LIBERTARIAN', 'GREEN', 'OTHER', name='party'), nullable=False),
    sa.Column('chamber', sa.Enum('HOUSE', 'SENATE', name='chamber'), nullable=False),
    sa.Column('leadership_role', sa.String(length=255), nullable=True),
    sa.Column('twitter_account', sa.String(length=100), nullable=True),
    sa.Column('facebook_account', sa.String(length=100), nullable=True),
    sa.Column('youtube_account', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('office', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('senate_class', sa.Integer(), nullable=True),
    sa.Column('state_rank', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_congressmen_bioguide_id'), 'congressmen', ['bioguide_id'], unique=True)
    op.create_index(op.f('ix_congressmen_id'), 'congressmen', ['id'], unique=False)
    op.create_table('bill_cosponsor',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('congressman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['congressman_id'], ['congressmen.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'congressman_id')
    )
    op.create_table('bill_sponsor',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('congressman_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['congressman_id'], ['congressmen.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'congressman_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_sponsor')
    op.drop_table('bill_cosponsor')
    op.drop_index(op.f('ix_congressmen_id'), table_name='congressmen')
    op.drop_index(op.f('ix_congressmen_bioguide_id'), table_name='congressmen')
    op.drop_table('congressmen')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_bill_id'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
