"""Add BillText and billID reference

Revision ID: c48e2a25ce55
Revises: 04194e790d0f
Create Date: 2025-03-23 19:22:37.173775

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c48e2a25ce55"
down_revision = "04194e790d0f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_texts",
        sa.Column("formatted_bill_id", sa.String(length=20), nullable=True),
    )
    op.create_index(
        op.f("ix_bill_texts_formatted_bill_id"),
        "bill_texts",
        ["formatted_bill_id"],
        unique=False,
    )
    op.create_foreign_key(None, "bill_texts", "bills", ["formatted_bill_id"], ["bill_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bill_texts", type_="foreignkey")
    op.drop_index(op.f("ix_bill_texts_formatted_bill_id"), table_name="bill_texts")
    op.drop_column("bill_texts", "formatted_bill_id")
    # ### end Alembic commands ###
