"""Use full state names

Revision ID: c685083c2c91
Revises: eb65642e0ff5
Create Date: 2025-03-23 10:10:55.058673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c685083c2c91"
down_revision = "eb65642e0ff5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "congressmen",
        "state",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "congressmen",
        "state",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
