"""Remove username field from User model

Revision ID: d02727f3fef4
Revises: 72c597951ab3
Create Date: 2025-03-27 23:00:04.252403

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d02727f3fef4"
down_revision = "72c597951ab3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    # ### end Alembic commands ###
