"""Drop class and rank

Revision ID: eb65642e0ff5
Revises: 83ddeb287674
Create Date: 2025-03-23 10:07:46.684573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb65642e0ff5"
down_revision = "83ddeb287674"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("congressmen", "state_rank")
    op.drop_column("congressmen", "senate_class")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "congressmen",
        sa.Column("senate_class", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "congressmen",
        sa.Column(
            "state_rank", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
