"""Add text versions

Revision ID: f403e3aaf73e
Revises: cc3108293e7c
Create Date: 2025-03-23 15:55:56.890906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f403e3aaf73e"
down_revision = "cc3108293e7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_texts",
        sa.Column("bill_id", sa.String(length=20), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("pdf_url", sa.String(length=500), nullable=True),
        sa.Column("formatted_text_url", sa.String(length=500), nullable=True),
        sa.Column("xml_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.bill_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bill_id", "date", name="uix_bill_text_version"),
    )
    op.create_index(
        op.f("ix_bill_texts_bill_id"), "bill_texts", ["bill_id"], unique=False
    )
    op.create_index(op.f("ix_bill_texts_id"), "bill_texts", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bill_texts_id"), table_name="bill_texts")
    op.drop_index(op.f("ix_bill_texts_bill_id"), table_name="bill_texts")
    op.drop_table("bill_texts")
    # ### end Alembic commands ###
