"""Add BillText back

Revision ID: f5dde0776bb6
Revises: 8fea8f4d78fd
Create Date: 2025-03-23 19:26:56.196063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f5dde0776bb6"
down_revision = "8fea8f4d78fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bill_texts_bill_id", table_name="bill_texts")
    op.drop_constraint("uix_bill_type", "bill_texts", type_="unique")
    op.create_unique_constraint("uix_bill_type", "bill_texts", ["formatted_bill_id", "type"])
    op.drop_constraint("bill_texts_bill_id_fkey", "bill_texts", type_="foreignkey")
    op.drop_column("bill_texts", "bill_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_texts",
        sa.Column("bill_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key("bill_texts_bill_id_fkey", "bill_texts", "bills", ["bill_id"], ["id"])
    op.drop_constraint("uix_bill_type", "bill_texts", type_="unique")
    op.create_unique_constraint("uix_bill_type", "bill_texts", ["bill_id", "type"])
    op.create_index("ix_bill_texts_bill_id", "bill_texts", ["bill_id"], unique=False)
    # ### end Alembic commands ###
