// Run with PGLITE_MODULE pointing to an installed @electric-sql/pglite module.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
const root=fileURLToPath(new URL('../../../../',import.meta.url));
await db.exec(`
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create table public.bill(id bigint primary key,title text,congress int,number int,type text,law_enacted_date date,created_at timestamptz,updated_at timestamp);
create table public.bill_text(id bigint primary key,bill_id bigint,date date,type text,html_file_path text,created_at timestamptz,updated_at timestamp);
create table public.bill_action(id bigint primary key,bill_id bigint,date date,text text,created_at timestamptz,updated_at timestamp);
create table public.bill_summary(id bigint primary key,bill bigint,date date,text text,created_at timestamptz);
create table public.agency_document(id bigint primary key,title text,subtype text,created_at timestamptz,updated_at timestamp);
create table public.court(id bigint primary key,remote_id text);
create table public.cluster(id bigint primary key,court_id bigint,case_name text,created_at timestamptz,updated_at timestamp);
create table public.court_opinion(id bigint primary key,cluster_id bigint,type text,created_at timestamptz,updated_at timestamp);
`);
await db.exec(readFileSync(root+'apps/web/supabase/migrations/20260820192741_replace_articles_with_briefs.sql','utf8'));
await db.exec(readFileSync(root+'apps/web/supabase/migrations/20260906223838_continuous_brief_pipeline.sql','utf8'));
await db.exec(readFileSync(root+'apps/web/supabase/migrations/20260906224831_brief_source_refresh_tracking.sql','utf8'));
const scalar=async (sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
const token='11111111-1111-4111-8111-111111111111', other='22222222-2222-4222-8222-222222222222';
await db.exec("insert into bill(id,title) values (1,'Example bill');");
assert.equal(await scalar('select revision from brief_source_change'),1);
await db.exec("update bill set updated_at=now() where id=1");
assert.equal(await scalar('select revision from brief_source_change'),1,'timestamps do not create developments');
assert.equal(await scalar("select begin_brief_source_run('congress',$1)",[token]),true);
assert.equal(await scalar("select begin_brief_source_run('congress',$1)",[other]),false);
await db.query("select end_brief_source_run('congress',$1,true)",[token]);
const meta=await scalar("select brief_source_bundle('bill',1)");
const packet={sources:[{id:'source_1',label:'Source',url:'https://example.gov/1'}],passages:[{id:'section_1',text:'Example source evidence.'}]};
const enqueue=async (fp='fp1',revision=1,metadata=meta,dev='development1')=>scalar("select enqueue_brief_job('bill',1,$1,$2,$3,'bill',$4,$5,90)",[revision,fp,dev,metadata,packet]);
const id=await enqueue();
assert.equal(await enqueue(),id,'idempotent discovery');
await db.query('select claim_brief_job($1)',[token]);
assert.equal((await db.query('select * from claim_brief_job($1)',[other])).rows.length,0,'exclusive claim');
await assert.rejects(()=>db.query("select finish_brief_job($1,$2,'verified','reason')",[id,token]),/Verification required/);
const draft={title:'Example headline',slug:'example-brief-1',dek:'A complete sentence.',points:[1,2,3].map(i=>({id:`point_${i}`,text:'Supported factual point.',source_refs:['source_1']})),context_markdown:'',policy_areas:['Government'],sources:packet.sources};
await db.query("select finish_brief_job($1,$2,'verified','Important',$3,$4,'writer','verifier','v1')",[id,token,draft,{passed:true,deterministic_passed:true}]);
assert.equal(await scalar('select publish_verified_brief($1)',[id]),null,'publication starts paused');
await db.exec('update brief_pipeline_settings set publication_enabled=true');
const published=await scalar('select publish_verified_brief($1)',[id]);
assert.ok(published);
assert.equal(await scalar('select publish_verified_brief($1)',[id]),published,'publication retry is idempotent');
await db.exec("update brief set title='Editor correction',auto_generated=false where id=1");
assert.equal(await scalar("select content->>'title' from brief_revision where brief_id=1"),'Example headline','revision history preserves old content');
await db.exec("update bill set title='A changed bill' where id=1");
const meta2=await scalar("select brief_source_bundle('bill',1)");
const id2=await enqueue('fp2',2,meta2);
await db.query('select claim_brief_job($1)',[token]);
await db.query("select finish_brief_job($1,$2,'verified','Important',$3,$4)",[id2,token,{...draft,slug:'example-brief-2'},{passed:true,deterministic_passed:true}]);
assert.equal(await scalar('select publish_verified_brief($1)',[id2]),null,'same development cannot duplicate existing coverage');
assert.equal(await scalar('select title from brief where id=1'),'Editor correction');
const id3=await enqueue('fp3',2,meta2,'development2');
await db.query('select claim_brief_job($1)',[token]);
await db.query("select finish_brief_job($1,$2,'verified','Important',$3,$4)",[id3,token,{...draft,slug:'example-brief-3'},{passed:true,deterministic_passed:true}]);
await db.exec("update bill set title='Changed during verification' where id=1");
assert.equal(await scalar('select publish_verified_brief($1)',[id3]),null,'source changes invalidate publication');
await db.query("select reserve_brief_api_call($1,'model','write',4)",[id]);
await assert.rejects(()=>db.query("select reserve_brief_api_call($1,'model','write',2)",[id]),/budget exhausted/);
assert.equal(await scalar("select reserve_brief_upstream_request('courtlistener',1)"),true);
assert.equal(await scalar("select reserve_brief_upstream_request('courtlistener',1)"),false);
assert.equal(await scalar("select has_function_privilege('anon','public.publish_verified_brief(bigint)','execute')"),false);
assert.equal(await scalar("select has_table_privilege('authenticated','public.brief_job','select')"),false);
assert.ok(await scalar('select brief_pipeline_overview()'));
// Expired workers can be reclaimed; a stale owner cannot finish the replacement's work.
await db.exec("insert into bill(id,title) values(2,'Second bill')");
const m2=await scalar("select brief_source_bundle('bill',2)");
const recover=await scalar("select enqueue_brief_job('bill',2,1,'recover','recover','bill',$1,$2,100)",[m2,packet]);
await db.query('select claim_brief_job($1)',[token]);
await db.exec("update brief_job set lease_until=now()-interval '1 minute' where id="+recover);
const reclaimed=(await db.query('select * from claim_brief_job($1)',[other])).rows[0];
assert.equal(reclaimed.id,recover);
await assert.rejects(()=>db.query("select finish_brief_job($1,$2,'skipped','stale worker')",[recover,token]),/lease lost/);
await db.query("select defer_brief_budget($1,$2,false)",[recover,other]);
assert.equal(await scalar('select attempts from brief_job where id=$1',[recover]),1);
// A clean automated correction keeps its URL and leaves a revision trail.
await db.exec("insert into bill(id,title) values(3,'Third bill')");
const m3=await scalar("select brief_source_bundle('bill',3)");
const first=await scalar("select enqueue_brief_job('bill',3,1,'third1','third','bill',$1,$2,100)",[m3,packet]);
await db.query('select claim_brief_job($1)',[token]);
await db.query("select finish_brief_job($1,$2,'verified','Important',$3,$4)",[first,token,{...draft,slug:'third-brief'},{passed:true,deterministic_passed:true}]);
const thirdBrief=await scalar('select publish_verified_brief($1)',[first]);
await db.exec("update bill set title='Third bill corrected' where id=3");
const m4=await scalar("select brief_source_bundle('bill',3)");
const correction=await scalar("select enqueue_brief_job('bill',3,2,'third2','third','bill',$1,$2,100)",[m4,packet]);
await db.query('select claim_brief_job($1)',[token]);
await db.query("select finish_brief_job($1,$2,'verified','Correction',$3,$4)",[correction,token,{...draft,title:'Corrected account',slug:'unused-new-slug'},{passed:true,deterministic_passed:true}]);
assert.equal(await scalar('select publish_verified_brief($1)',[correction]),thirdBrief);
assert.equal(await scalar('select slug from brief where id=$1',[thirdBrief]),'third-brief');
assert.equal(await scalar('select count(*) from brief_revision where brief_id=$1',[thirdBrief]),1);
await db.query("select note_brief_source_refresh('bill',3)");
assert.equal(await scalar("select revision from brief_source_change where item_type='bill' and item_id=3"),3);
console.log('PASS: migration, change tracking, source locks, duplicate discovery, exclusive claims, verification gate, pause, atomic/idempotent publication, revisions, editor protection, stale evidence, budgets, and permissions');
await db.close();
