import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create table bill(id bigint primary key);
create table sponsored_bills(bill_id bigint,congressman_id bigint);
create table cosponsored_bills(bill_id bigint,congressman_id bigint);
create table bill_text(bill_id bigint,date date,type text,fallback_key text,pdf_url text,html_url text,xml_url text,pdf_file_path text,html_file_path text,xml_file_path text);
create table bill_action(bill_id bigint,date date,text text,type text);
create table bill_summary(bill bigint,date date,text text);
`);
const original=readFileSync(new URL('../../../../apps/web/supabase/migrations/20260819160724_improve_data_sync_integrity.sql',import.meta.url),'utf8');
await db.exec(original.match(/create or replace function public.replace_bill_actions\([\s\S]*?\n\$\$;/)[0]);
await db.exec(readFileSync(new URL('../../../../apps/web/supabase/migrations/20260919165423_tolerate_partial_congress_records.sql',import.meta.url),'utf8'));
await db.exec(`insert into bill(id,sync_pending) values(1,true);
insert into sponsored_bills values(1,7); insert into cosponsored_bills values(1,8);
insert into bill_text(bill_id,date,type,html_url,html_file_path,pdf_url,pdf_file_path) values(1,'2026-09-01','Introduced','html','stored.html','pdf','stored.pdf');
insert into bill_action values(1,'2026-09-01','Introduced','Intro');
insert into bill_summary values(1,'2026-09-01','Existing summary');`);
const scalar=async(sql,params=[])=>Object.values((await db.query(sql,params)).rows[0])[0];
const complete=(cosponsors,texts,actions=null)=>db.query('select complete_bill_sync(1,$1,$2,$3,$4,$5,$6)',[null,cosponsors,texts,actions,null,['cosponsors']]);
await complete(null,null);
assert.equal(await scalar('select congressman_id from cosponsored_bills'),8);
assert.equal(await scalar('select html_file_path from bill_text'),'stored.html');
assert.equal(await scalar('select text from bill_summary'),'Existing summary');
assert.equal(await scalar('select sync_pending from bill'),false);
await complete([],[{date:'2026-09-01',type:'Introduced',html_url:'html',pdf_url:'pdf',html_file_path:'fresh.html'}]);
assert.equal(await scalar('select count(*) from cosponsored_bills'),0,'confirmed empty collection clears old rows');
assert.equal(await scalar('select html_file_path from bill_text'),'fresh.html');
assert.equal(await scalar('select pdf_file_path from bill_text'),'stored.pdf','failed alternate download preserves existing matching format');
await complete(null,[{date:'2026-09-01',type:'Introduced',html_url:'changed-html',pdf_url:'changed-pdf'}]);
assert.equal(await scalar('select pdf_file_path from bill_text'),null,'changed URL cannot borrow stale text');
await assert.rejects(()=>complete(null,[],[{date:'not-a-date',text:'Invalid'}]));
assert.equal(await scalar('select count(*) from bill_text'),1,'a malformed replacement rolls back all child changes');
assert.equal(await scalar("select has_function_privilege('anon','public.complete_bill_sync(bigint,jsonb,jsonb,jsonb,jsonb,jsonb,text[])','execute')"),false);
await db.close();
console.log('Congress partial-data database checks passed');
