-- Article content model for media-style coverage
set search_path = public;

create table if not exists article (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    status text not null default 'draft',
    title text not null,
    slug text unique,
    dek text,
    excerpt text,
    summary text,
    body jsonb,
    body_markdown text,
    reading_time smallint,
    hero_image_url text,
    source_urls text[] not null default '{}',
    auto_generated boolean not null default true,
    prompt_template text,
    generation_metadata jsonb,
    generated_at timestamptz,
    published_at timestamptz,
    is_featured boolean not null default false,
    featured_until timestamptz,
    primary_item_type text not null,
    primary_item_id bigint not null,
    author text,
    agent_identifier text,
    editor_notes text,
    views_count bigint not null default 0,
    clickthroughs bigint not null default 0,
    constraint article_status_check check (
        status in ('draft', 'review', 'scheduled', 'published', 'archived')
    ),
    constraint article_primary_item_type_check check (
        primary_item_type in ('bill', 'law', 'agency_document', 'cluster', 'executive_order')
    ),
    constraint article_reading_time_check check (
        reading_time is null or reading_time >= 0
    ),
    constraint article_views_count_check check (views_count >= 0),
    constraint article_clickthroughs_check check (clickthroughs >= 0)
);

create index if not exists article_primary_item_idx
    on article (primary_item_type, primary_item_id);

create index if not exists article_status_published_idx
    on article (status, published_at desc);

create or replace function public.set_article_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_public_article_updated_at on article;

create trigger set_public_article_updated_at
before update on article
for each row
execute procedure public.set_article_updated_at();

create table if not exists article_related_item (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    article_id bigint not null references article (id) on delete cascade,
    item_type text not null,
    item_id bigint not null,
    relation_role text,
    constraint article_related_item_type_check check (
        item_type in ('bill', 'law', 'agency_document', 'cluster', 'executive_order')
    )
);

create index if not exists article_related_item_article_idx
    on article_related_item (article_id);

create index if not exists article_related_item_lookup_idx
    on article_related_item (item_type, item_id);
